"""Unit tests for the ``.out`` reference-output parser.

These cover the corners of :mod:`pybmodes.io.out_parser` that ``test_io.py``
does not exercise directly:
  * blade/tower beam-type detection from header
  * the synthetic mode-block parser (mode header, column row, data rows)
  * malformed / short / non-numeric data rows are tolerated
  * the ``BModeOutput`` collection helpers (``__len__``, ``__getitem__``,
    ``frequencies``)
  * ``ModeShape`` blade and tower property aliases (``flap_disp``/``ss_disp``)
"""

from __future__ import annotations

import textwrap

import numpy as np
import pytest

from pybmodes.io.out_parser import BModeOutput, ModeShape, read_out


def _write(tmp_path, name, body):
    path = tmp_path / name
    path.write_text(textwrap.dedent(body).lstrip("\n"), encoding="utf-8")
    return path


# ===========================================================================
# Beam-type detection
# ===========================================================================

class TestBeamTypeDetection:

    def test_blade_keyword(self, tmp_path):
        f = _write(tmp_path, "blade.out", """
            pybmodes results
            rotating blade frequencies & mode shapes
            ---------- Mode No.  1 (freq = 1.0E+00 Hz)
            span flap flap_slope lag lag_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.0 0.0 0.0 0.0
        """)
        out = read_out(f)
        assert out.beam_type == "blade"

    def test_tower_keyword(self, tmp_path):
        f = _write(tmp_path, "tower.out", """
            pybmodes results
            tower frequencies & mode shapes
            ---------- Mode No.  1 (freq = 0.5E+00 Hz)
            span ss ss_slope fa fa_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 0.5 0.0 1.0 0.0 0.0
        """)
        out = read_out(f)
        assert out.beam_type == "tower"

    def test_default_to_blade_when_neither_keyword(self, tmp_path):
        f = _write(tmp_path, "neither.out", """
            pybmodes results
            ---------- Mode No.  1 (freq = 1.0E+00 Hz)
            span c1 c2 c3 c4 twist
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.0 0.0 0.0 0.0
        """)
        out = read_out(f)
        # Default beam_type is 'blade' when no header keyword matches.
        assert out.beam_type == "blade"


# ===========================================================================
# Mode-block parsing
# ===========================================================================

class TestModeBlockParsing:

    def test_single_mode(self, tmp_path):
        f = _write(tmp_path, "one.out", """
            generated by pybmodes
            mytitle
            rotating blade frequencies & mode shapes
            ---------- Mode No.  1 (freq = 0.42E+00 Hz)
            span flap flap_slope lag lag_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            0.5 0.3 0.4 0.0 0.0 0.0
            1.0 1.0 0.5 0.0 0.0 0.0
        """)
        out = read_out(f)
        assert len(out) == 1
        m = out[0]
        assert m.mode_number == 1
        assert m.frequency == pytest.approx(0.42)
        assert m.span_loc.tolist() == [0.0, 0.5, 1.0]
        assert m.flap_disp[-1] == pytest.approx(1.0)

    def test_two_modes(self, tmp_path):
        f = _write(tmp_path, "two.out", """
            ==================================================================
            pybmodes
            tower frequencies & mode shapes
            ---------- Mode No.  1 (freq = 0.30E+00 Hz)
            span ss ss_slope fa fa_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 0.0 0.0 1.0 0.5 0.0
            ---------- Mode No.  2 (freq = 0.95E+00 Hz)
            span ss ss_slope fa fa_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.4 0.0 0.0 0.0
        """)
        out = read_out(f)
        assert len(out) == 2
        assert out[0].frequency == pytest.approx(0.30)
        assert out[1].frequency == pytest.approx(0.95)
        # tower aliases on mode 1: fa dominant
        assert out[0].fa_disp[-1] == pytest.approx(1.0)
        assert out[0].ss_disp[-1] == pytest.approx(0.0)
        # mode 2: ss dominant
        assert out[1].ss_disp[-1] == pytest.approx(1.0)

    def test_short_rows_ignored(self, tmp_path):
        # Rows with <6 numeric tokens should be silently dropped, not crash.
        f = _write(tmp_path, "short.out", """
            pybmodes
            rotating blade frequencies & mode shapes
            ---------- Mode No.  1 (freq = 1.0E+00 Hz)
            span flap flap_slope lag lag_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            BAD ROW
            1.0 1.0 0.0 0.0 0.0 0.0
        """)
        out = read_out(f)
        assert len(out[0].span_loc) == 2

    def test_non_numeric_row_ignored(self, tmp_path):
        f = _write(tmp_path, "bad.out", """
            pybmodes
            rotating blade frequencies & mode shapes
            ---------- Mode No.  1 (freq = 1.0E+00 Hz)
            span flap flap_slope lag lag_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            this row has 6 tokens but not numeric
            1.0 1.0 0.0 0.0 0.0 0.0
        """)
        out = read_out(f)
        # ValueError on float() should silently drop the row
        assert len(out[0].span_loc) == 2

    def test_col_names_captured(self, tmp_path):
        f = _write(tmp_path, "cols.out", """
            pybmodes
            tower frequencies & mode shapes
            ---------- Mode No.  3 (freq = 1.5E+00 Hz)
            span_loc s-s s-s_slope f-a f-a_slope twist
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 0.0 0.0 1.0 0.0 0.0
        """)
        out = read_out(f)
        assert out[0].col_names[0] == "span_loc"
        assert "twist" in out[0].col_names


# ===========================================================================
# BModeOutput collection helpers
# ===========================================================================

class TestBModeOutputCollection:

    @pytest.fixture
    def out(self, tmp_path):
        f = _write(tmp_path, "multi.out", """
            pybmodes
            rotating blade frequencies & mode shapes
            ---------- Mode No.  1 (freq = 1.0E+00 Hz)
            a b c d e f
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.0 0.0 0.0 0.0
            ---------- Mode No.  2 (freq = 2.0E+00 Hz)
            a b c d e f
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.0 0.0 0.0 0.0
            ---------- Mode No.  3 (freq = 3.5E+00 Hz)
            a b c d e f
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.0 0.0 0.0 0.0
        """)
        return read_out(f)

    def test_len(self, out):
        assert len(out) == 3

    def test_indexing(self, out):
        assert out[0].mode_number == 1
        assert out[2].frequency == pytest.approx(3.5)

    def test_frequencies_returns_array(self, out):
        f = out.frequencies()
        assert isinstance(f, np.ndarray)
        assert f.tolist() == [1.0, 2.0, 3.5]

    def test_source_file_attached(self, out, tmp_path):
        assert out.source_file is not None
        assert out.source_file.parent == tmp_path


# ===========================================================================
# ModeShape blade/tower property aliases
# ===========================================================================

class TestModeShapeAliases:

    def _make(self) -> ModeShape:
        span = np.array([0.0, 0.5, 1.0])
        c1 = np.array([0.0, 0.1, 0.2])
        c2 = np.array([0.0, 0.2, 0.3])
        c3 = np.array([0.0, 0.3, 0.4])
        c4 = np.array([0.0, 0.4, 0.5])
        tw = np.array([0.0, 0.0, 0.0])
        return ModeShape(
            mode_number=1,
            frequency=1.0,
            span_loc=span,
            col1=c1,
            col2=c2,
            col3=c3,
            col4=c4,
            twist=tw,
        )

    def test_blade_aliases(self):
        m = self._make()
        np.testing.assert_array_equal(m.flap_disp, m.col1)
        np.testing.assert_array_equal(m.flap_slope, m.col2)
        np.testing.assert_array_equal(m.lag_disp, m.col3)
        np.testing.assert_array_equal(m.lag_slope, m.col4)

    def test_tower_aliases(self):
        m = self._make()
        np.testing.assert_array_equal(m.ss_disp, m.col1)
        np.testing.assert_array_equal(m.ss_slope, m.col2)
        np.testing.assert_array_equal(m.fa_disp, m.col3)
        np.testing.assert_array_equal(m.fa_slope, m.col4)


# ===========================================================================
# Empty / minimal files
# ===========================================================================

class TestEmptyOrMinimal:

    def test_no_modes(self, tmp_path):
        f = _write(tmp_path, "empty.out", """
            pybmodes
            rotating blade frequencies & mode shapes
        """)
        out = read_out(f)
        assert len(out) == 0
        assert out.frequencies().tolist() == []

    def test_isinstance_bmodeoutput(self, tmp_path):
        f = _write(tmp_path, "min.out", """
            pybmodes
            rotating blade frequencies & mode shapes
            ---------- Mode No.  1 (freq = 1.0E+00 Hz)
            a b c d e f
            0.0 0.0 0.0 0.0 0.0 0.0
            1.0 1.0 0.0 0.0 0.0 0.0
        """)
        out = read_out(f)
        assert isinstance(out, BModeOutput)
